namespace Jmelosegui.Mvc.GoogleMap
{
    public enum  ControlPosition
    {
        [ClientSideEnumValue("'BOTTOM_CENTER'")]
        BottomCenter,
        [ClientSideEnumValue("'BOTTOM_LEFT'")]
        BottomLeft,
        [ClientSideEnumValue("'BOTTOM_RIGHT'")]
        BottomRight,
        [ClientSideEnumValue("'LEFT_BOTTOM'")]
        LeftBottom,
        [ClientSideEnumValue("'RIGHT_BOTTOM'")]
        RightBottom,
        [ClientSideEnumValue("'LEFT_CENTER'")]
        LeftCenter,
        [ClientSideEnumValue("'RIGHT_CENTER'")]
        RightCenter,
        [ClientSideEnumValue("'TOP_CENTER'")]
        TopCenter,
        [ClientSideEnumValue("'TOP_LEFT'")]
        TopLeft,
        [ClientSideEnumValue("'TOP_RIGHT'")]
        TopRight,
        [ClientSideEnumValue("'LEFT_TOP'")]
        LeftTop,
        [ClientSideEnumValue("'RIGHT_TOP'")]
        RightTop
    }
}
